### ISSUE TITLE
参数检查模块arg_schema_checker

### ISSUE THREAD

**Issue by liubaohai** [bsc-s2/pykit#181]
根据yaml配置，校验参数

**Comment by drmingdrmer** [comment]
给出实现的例子, 参考...尽量多给点信息...

**Comment by liubaohai** [comment]
```
x:
  checker:
    type: float
    min: -100
    max: 100
  required: true

y:
  checker:
    type: float
    not: [0, ]
  required: true

op:
  checker:
    type: string
    enum:
      - bar
      - foo
  required: false
```

```
a = {
    'x': 1,
    'y': 2,
    'op': 'foo',
}
```
检查a中每个字段是否符合上面的预先设置的类型
