### ISSUE TITLE
new module: `cluster.server`

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/pykit#193]
参考 s2中的代码: 
- `s2node.py`
- `disk.py`
- `hardware.py`
- `partition.py`

### Required features:

- [ ] `server_id`:
  - [ ] make `server_id`
  - [ ] check `server_id`
- [ ] `serverrec`
  - [ ] make a `serverrec` dict with:
    - collected physical field: `pub_ips`, `inn_ips`, `hostname`, `server_id`, `memory`, `cpu`.
    - user specified field: `idc`, `idc_type`, `roles`(as a dict whose values are `1`) and other fields if needed.
    - disk drive infos.
    - mounted path.
  - [ ] update field if it changed on local host.
  - [ ] make a string about `serverrec` for human reading and logging
- [ ] drive:
  - [ ] add config field for drives mount point base dir, e.g. `/s2/drive`, or `/ec/drive`.
  - [ ] make `drive_id`, with arguments: `server_id`, `mount_point_index`, `mount_seq`.
  - [ ] parse `drive_id` into a `dict` that contains separated fields.
  - [ ] validate `drive_id`
  - [ ] make a `driverec`(drive record): fields include: `drive_id`, `media`, `readonly`, `is_del`.
  - [ ] make string to represent a `driverec` for human and logging.
- [ ] `idc`
  - [ ] check `idc`: `.l1-name.l2-name...`
  - [ ] estimate distance between two `idc`: reference: `s2/src/netutil.py: idc_distance(a,b)`.

---

### `serverrec` structure

```yaml
server_id: "x"
pub_ips: []
inn_ips: []
hostname: "x"
memory: 1024 # byte
cpu: blabla
idc: .dx.guangdong
idc_type: "center"
roles:
  blockserver: 1
  proxy: 1
  coordinator: 1
  ...
#max_mount_index: 12 # index of the last time mount a drive
#drives:
  # a drive should be mounted and managed by cluster.
  #"<drive_id>":
    #media_type: "ATA"
    #readonly: 0|1
    #is_del: 0|1
    #capacity: 123 # byte
    #fs: "xfs" 
  ...:
mountpoints:
  # mount but not managed. such as root fs etc.
  "<path>":
    capacity: 123 # byte
    fs: "xfs"
  ...:
```
