### ISSUE TITLE
zkutil: 增加初始化zknode hierarchy的函数

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/pykit#205]
用来对刚建立起来的zk集群做初始化, 初始化树形结构, 配置权限和节点默认值.

实现幂等操作: 允许初始化一半中断后重新运行得到同样的结果.

`zkutil.init_hierarchy(hierarchy, users)`

dict users的结构(表示每个hierarchy中提到的用户):

```yaml
user_1: "<password>"
user_2: "<password>"
```

举个🌰:

```yaml
ec-cluster:
  __val__: "json, optional, by default a '{}'"
  __acl__: # optional, by default TODO
    user_1: "[cdrwa]{0,5}"
    user_2: "[cdrwa]{0,5}"
    ...
  servers:
    "<server_id>": {...}
```

说明:

- 子节点的 `__acl__` 如果没有指定则集成上级的.
- `__val__`: 表示节点的内容, 对非叶子节点一般没有必要指定. 一般val都使用json编码的数据. 如果没有指定则使用 `{}`,表示一个空json dict.
